# Generated by Django 3.1.13 on 2021-08-13 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('status_order', models.IntegerField(choices=[(0, 'CONFIRMADO'), (1, 'EM PREPARAÇÃO'), (2, 'FINALIDADO'), (3, 'CANCELADO')], default=0, verbose_name='Status')),
                ('comments', models.CharField(blank=True, max_length=200, verbose_name='Observações')),
                ('type', models.IntegerField(choices=[(0, 'LOJA'), (1, 'DELIVERY')], default=0, verbose_name='Tipo')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Pedido de Venda',
                'verbose_name_plural': 'Pedidos de Venda',
            },
        ),
    ]
