CONFIRMED, IN_PREPARATION, FINISHED, CANCELED = 0, 1, 2, 3

STATUS_ORDER = (
    (CONFIRMED, "CONFIRMADO"),
    (IN_PREPARATION, "EM PREPARAÇÃO"),
    (FINISHED, "FINALIZADO"),
    (CANCELED, "CANCELADO"),
)

STORE, DELIVERY, RETIRADA = 0, 1 ,2

TYPE_ORDER = ((STORE, "LOJA"), (DELIVERY, "DELIVERY"), (RETIRADA, "RETIRADA"))
