# Generated by Django 3.1.13 on 2021-12-05 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('comments', models.CharField(blank=True, max_length=200, verbose_name='Observações')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
            options={
                'verbose_name': 'Pedido de Venda',
                'verbose_name_plural': 'Pedidos de Venda',
            },
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Status do Pedido',
                'verbose_name_plural': 'Status dos Pedidos',
            },
        ),
        migrations.CreateModel(
            name='TypeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipos de Pedidos',
                'verbose_name_plural': 'Tipo de Pedido',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('recipe_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.recipemenu', verbose_name='Receitas')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_order', to='order.salesorder')),
            ],
            options={
                'verbose_name': 'ReceitaMenu Pedido',
                'verbose_name_plural': 'ReceitasMenu Pedidos',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('product_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.productmenu', verbose_name='Produtos')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='order.salesorder')),
            ],
            options={
                'verbose_name': 'ProdutoMenu Pedido',
                'verbose_name_plural': 'ProdutoMenus Pedidos',
            },
        ),
        migrations.AddField(
            model_name='salesorder',
            name='status_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.statusorder'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='type_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.typeorder'),
        ),
    ]
