# Generated by Django 3.1.13 on 2021-10-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('description', models.CharField(max_length=200)),
                ('weekday', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-Feira'), (2, 'Terça-Feira'), (3, 'Quarta-Feira'), (4, 'Quinta-Feira'), (5, 'Sexta-Feira'), (6, 'Sábado')], default=0, verbose_name='Dia da Semana')),
                ('status', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1)),
            ],
            options={
                'verbose_name': 'Cardápio',
                'verbose_name_plural': 'Cardápio',
            },
        ),
        migrations.CreateModel(
            name='PortionMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='Cardápio')),
                ('product', models.ForeignKey(limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Adicionais')),
            ],
            options={
                'verbose_name': 'Porção',
                'verbose_name_plural': 'Porções',
            },
        ),
        migrations.CreateModel(
            name='LunchMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='Cardápio')),
                ('revenue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.revenue', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Lanche',
                'verbose_name_plural': 'Lanches',
            },
        ),
        migrations.CreateModel(
            name='DrinkMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='Cardápio')),
                ('product', models.ForeignKey(limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Adicionais')),
            ],
            options={
                'verbose_name': 'Bebida',
                'verbose_name_plural': 'Bebidas',
            },
        ),
        migrations.CreateModel(
            name='DessertMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='Cardápio')),
                ('product', models.ForeignKey(limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Adicionais')),
            ],
            options={
                'verbose_name': 'Sobremesa',
                'verbose_name_plural': 'Sobremesas',
            },
        ),
        migrations.CreateModel(
            name='AdditionalMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='Cardápio')),
                ('product', models.ForeignKey(limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Adicionais')),
            ],
            options={
                'verbose_name': 'Adicional',
                'verbose_name_plural': 'Adicionais',
            },
        ),
    ]
