# Generated by Django 3.1.13 on 2021-10-05 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('description', models.CharField(max_length=200)),
                ('weekday', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-Feira'), (2, 'Terça-Feira'), (3, 'Quarta-Feira'), (4, 'Quinta-Feira'), (5, 'Sexta-Feira'), (6, 'Sábado')], default=0, verbose_name='Dia da Semana')),
                ('status', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1)),
            ],
            options={
                'verbose_name': 'Cardápio',
                'verbose_name_plural': 'Cardápio',
            },
        ),
        migrations.CreateModel(
            name='RevenueMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('type', models.IntegerField(choices=[(0, 'Bebida'), (1, 'Lanche'), (2, 'Sobremesa'), (3, 'Porção')], default=0, verbose_name='Tipo de Receita')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='Cardápio')),
                ('revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.revenue', verbose_name='Receitas')),
            ],
            options={
                'verbose_name': 'Cardapio de Receita',
                'verbose_name_plural': 'Cardapio de Receitas',
            },
        ),
        migrations.CreateModel(
            name='ProductMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_in', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('type', models.IntegerField(choices=[(0, 'Bebida'), (1, 'Doce'), (2, 'Adicional')], default=0, verbose_name='Tipo de Produto')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='Cardápio')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Produtos')),
            ],
            options={
                'verbose_name': 'Cardapio de Produto',
                'verbose_name_plural': 'Cardapio de Produtos',
            },
        ),
    ]
